# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39077302431634838af6d9d18dd5a0c6f188f89c59db61ac7e9e26112c08c5319d907d16c06409227f488e455e7e86596b0c8e91d5ffec3e7570c116cd00fa1d

test:
  secret_key_base: 704498f264e7b907002104b007a9bcdbe946e367b5da61ebcab879c30dfe6a5e7a1e58424db28cfeade0c4023a6a1126cf2b5464c1ae1441d6f659c2776e677d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
